### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by christianfrei** [s3inlc/PRIME-Client#6]
Traceback (most recent call last):
  File "/usr/lib/python3.5/random.py", line 253, in choice
    i = self._randbelow(len(seq))
  File "/usr/lib/python3.5/random.py", line 230, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 384, in <module>
    start()
  File "test.py", line 349, in start
    getMessage(s)
  File "test.py", line 175, in getMessage
    slave2 = random.choice(serverList)
  File "/usr/lib/python3.5/random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

**Comment by christianfrei** [comment]
fixed in 911a878a08ec33c6adbdaa294f5b03312b701da9
